### ISSUE TITLE
Consider renaming modules

### ISSUE THREAD

**Issue by snicoll** [jihor/hiatus-spring-boot#1]
I've stumbled upon this project following a PR you've just opened in the Spring Boot project. 

Could you please consider renaming your modules? As [described in the documentation](http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-custom-starter-naming) we'd like 3rd party contribution's module name not to start with `spring-boot`

Thanks!

**Comment by jihor** [comment]
@snicoll thanks for the tip, will do.

**Comment by jihor** [comment]
Modules and project are now to 'hiatus-spring-boot-starter' in accordance with Spring Boot guidelines.

**Comment by snicoll** [comment]
Awesome, on my side I've created https://github.com/spring-projects/spring-boot/issues/9846
